name: TestingPlugin
version: '${project.version}'
main: me.mizab.testingplugin.TestingPlugin
api-version: 1.19
commands:
  menu:
    description: open a inventory
  nightvision:
    description: give night vision
  fly:
    description: fly
